name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  testsCPU:
    name: CPU Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update packages
      run: sudo apt-get update
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install numpy
        pip3 install requests
        pip3 install tqdm
        pip3 install torch>=1.7.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html --use-deprecated=html5lib

    - name: Test with unittest
      run: python3 -m unittest

